---
- name: push GitLab repo file (Debian/Ubuntu)
  ansible.builtin.template:
    src: templates/gitlab.sources.list.j2
    dest: "/etc/apt/sources.list.d/gitlab_gitlab-{{ edition_abbreviation }}.list"
    owner: root
    group: root
    mode: '0644'
  register: repo_file_pushed

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - repo_file_pushed.changed